# SPDX-FileCopyrightText: 2026 Onur Tuncer and Stereon contributors
# SPDX-License-Identifier: MPL-2.0
#
# Licensing for files that cannot carry a header comment (ADR-0008).
# Source files carry their own SPDX header; see docs/license-header.txt.
# Corpus files keep their original licences, recorded in corpus/LICENSES.md.

version = 1

[[annotations]]
path = [
    "*.md", "**/*.md",
    "*.json", "**/*.json",
    "**/*.png",
    "**/*.svg",
    "docs/license-header.txt",
    ".github/**",
    ".gitignore",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Onur Tuncer and Stereon contributors"
SPDX-License-Identifier = "MPL-2.0"
